version = 0.1

[default.deploy.parameters]
stack_name = "pokedex-api"
resolve_s3 = true
s3_prefix = "pokedex-api"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true

[default.global.parameters]
region = "eu-north-1"
