AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Pokedex API

Globals:
  Function:
    Runtime: nodejs22.x
    CodeUri: .
    MemorySize: 128
    Timeout: 10
    Environment:
      Variables:
        APP_ENV: aws

Resources:
  PokedexApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization,X-Requested-With'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: arn:aws:cognito-idp:eu-north-1:630956767633:userpool/eu-north-1_8obb1hQXa

  HealthCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/healthCheck.healthCheckHandler
      Events:
        HealthCheckApi:
          Type: Api
          Properties:
            RestApiId: !Ref PokedexApi
            Path: /healthCheck
            Method: get
            Auth:
              Authorizer: NONE
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - src/handlers/healthCheck.ts
        Target: node22

  PokedexFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/pokemon/index.handler
      Environment:
        Variables:
          TABLE_NAME: pokedex-dynamo
      Policies:
        DynamoDBCrudPolicy:
            TableName: pokedex-dynamo
      Events:
        PokemonGetList:
          Type: Api
          Properties:
            RestApiId: !Ref PokedexApi
            Path: /pokemon
            Method: get
            Auth:
              Authorizer: NONE

        PokemonCreate:
          Type: Api
          Properties:
            RestApiId: !Ref PokedexApi
            Path: /pokemon
            Method: post

        PokemonGetDetails:
          Type: Api
          Properties:
            RestApiId: !Ref PokedexApi
            Path: /pokemon/{id}
            Method: get
            Auth:
              Authorizer: NONE

        PokemonUpdate:
          Type: Api
          Properties:
            RestApiId: !Ref PokedexApi
            Path: /pokemon/{id}
            Method: put

        PokemonDelete:
          Type: Api
          Properties:
            RestApiId: !Ref PokedexApi
            Path: /pokemon/{id}
            Method: delete
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - src/handlers/pokemon/index.ts
        Target: node22

Outputs:
  HealthCheckApiUrl:
    Description: URL healthCheck
    Value: !Sub "https://${PokedexApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/healthCheck"

  PokedexApiUrl:
    Description: URL API pokemon
    Value: !Sub "https://${PokedexApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/pokemon"