AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: Cognito authentication resources for Pokedex.

Parameters:
    ServiceName:
        Type: String
        Description: Name of the service
    StackSuffix:
        Type: String
        Description: Suffix of stack name (env or env-prId)

Resources:
    UserPool:
        Type: AWS::Cognito::UserPool
        DeletionPolicy: Delete
        UpdateReplacePolicy: Delete
        Properties:
            UserPoolName: !Sub "${ServiceName}-${StackSuffix}-user-pool"
            UsernameAttributes:
                - email
            AutoVerifiedAttributes:
                - email
            Policies:
                PasswordPolicy:
                    MinimumLength: 8
                    RequireLowercase: true
                    RequireUppercase: true
                    RequireNumbers: true
                    RequireSymbols: false
            Schema:
                - Name: email
                  Required: true
                  Mutable: true
            AdminCreateUserConfig:
                AllowAdminCreateUserOnly: false

    UserPoolClient:
        Type: AWS::Cognito::UserPoolClient
        Properties:
            ClientName: !Sub "${ServiceName}-${StackSuffix}-user-pool-client"
            UserPoolId: !Ref UserPool
            GenerateSecret: false
            ExplicitAuthFlows:
                - ALLOW_USER_PASSWORD_AUTH
                - ALLOW_REFRESH_TOKEN_AUTH
                - ALLOW_USER_SRP_AUTH
            PreventUserExistenceErrors: ENABLED
            AllowedOAuthFlowsUserPoolClient: true
            AllowedOAuthFlows:
                - code
            AllowedOAuthScopes:
                - openid
                - email
            SupportedIdentityProviders:
                - COGNITO
            CallbackURLs:
                - http://localhost:3000/oauth2-redirect.html
                - https://diddykong57.github.io/Pokedex/oauth2-redirect.html
            LogoutURLs:
                - http://localhost:3000/
                - https://diddykong57.github.io/Pokedex/

    UserPoolDomain:
        Type: AWS::Cognito::UserPoolDomain
        Properties:
            Domain: !Sub "pokedex-diddykong57-auth"
            UserPoolId: !Ref UserPool

    AdminGroup:
        Type: AWS::Cognito::UserPoolGroup
        Properties:
            GroupName: admin
            Description: Admin users group
            UserPoolId: !Ref UserPool

Outputs:
    UserPoolId:
        Description: Cognito User Pool ID
        Value: !Ref UserPool

    UserPoolArn:
        Description: Cognito User Pool ARN
        Value: !GetAtt UserPool.Arn

    UserPoolClientId:
        Description: Cognito User Pool Client ID
        Value: !Ref UserPoolClient

    AdminGroupName:
        Description: Cognito admin group name
        Value: !Ref AdminGroup
